### ISSUE TITLE
Hello, 有个开源项目合作邀请～

### ISSUE THREAD

**Issue by jinmingpang** [limichange/zaku#69]
你好，我看到你在开发拖拽UI编辑器，和我发起的一个开源项目的需求和解决的问题类似。只是选择的基础库和实现的方法不同。

这里是项目地址。 [rt-admin](https://github.com/CareyToboo/rt-admin/tree/cli),希望大佬抽空能有时间看下，看是否有兴趣合作开源。目前核心用户群是：企业内部系统。

RTA主要目标：是做一个可在线UI编辑器生成管理系统，实现基本脱离开发人员。类似于“[简道云](https://www.jiandaoyun.com/)”。

思路主要分三步：【目前处于第一阶段50%】
- 写 cli、core、editor 基础npm包，可作为第三方引入，快速接入admin相关管理系统开发。
- 封装 高可复用 模块，作为admin项目标配。
- 将项目物理配置文件全部用 接口api，或者服务端文件生成， 移到云端，实现在线生成admin系统。

> 有兴趣，可以加入Q群，期待回复～

**Comment by limichange** [comment]
……所以你的Q群呢？

**Comment by jinmingpang** [comment]
Q群： 1037291990 。 不好意思，忘了贴出来，还以为在项目readme里面。欢迎加入～
